#sudo: required

language: python

services:
  - docker

install: ''

script:
  - docker-compose run --rm foliant make site --with mkdocs

deploy:
  - provider: pages:git
    edge: true
    token: $GITHUB_TOKEN
    #provider: pages
    local-dir: flnt-test.mkdocs
    #skip-cleanup: true
    #cleanup: true
    #github-token: $GITHUB_TOKEN
    keep-history: true
    verbose: true
    on:
      branch: master
