openapi: 3.0.1
info:
  title: Sample API from reqres.in
  description: Получить список пользователей или одного пользователя по ИД
  version: 1.0.0
servers:
- url: https://reqres.in/api
tags:
- name: Пользователи
  description: Информация о пользователях
  externalDocs:
    description: Подробнее
    url: https://reqres.in/
paths:
  /users:
    get:
      tags:
      - Пользователи
      summary: Возвращает список пользователей.
      responses:
        200:
          description: OK
          content: {}
  /users/{userId}:
    get:
      tags:
      - Пользователи
      summary: Возвращает пользователя по ИД.
      parameters:
      - name: userId
        in: path
        description: ИД пользователя.
        required: true
        schema:
          minimum: 1
          type: integer
      responses:
        200:
          description: Пользователь.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Неверно указан ИД.
          content: {}
        404:
          description: Пользователь не найден.
          content: {}
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 4
        email:
          type: string
          example: eve.holt@reqres.in
        first_name:
          type: string
          example: Eve Holt
        last_name:
          type: string
          example: Holt
        avatar:
          type: string
          example: https://s3.amazonaws.com/uifaces/faces/twitter/marcoramires/128.jpg
